[project]
name = "treetracer"
version = "0.1.0"
description = "An app to visualize phylogenetic tree topology convergence"
readme = "README.md"
authors = [
    { email = "samuel.hong@kuleuven.be" }
]
requires-python = ">=3.13"
dependencies = [
    "dash>=4.1.0",
    "dash-iconify",
    "dash-mantine-components",
    "dendropy>=5.0.8",
    "pandas",
    "rapidtrees==0.4.0",
    "plotly",
    "psutil>=7.0.0",
    "numpy",
    "scipy",
    "kaleido",
    "pywebview>=6.1",
]

[project.scripts]
treetracer = "treetracer:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.setuptools.package-data]
"treetracer" = ["assets/*"]
